//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingMap.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CaptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackingMap.UI.CaptionResource", typeof(CaptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فعالیت.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه به مسیر.
        /// </summary>
        public static string AddCustomerRoute {
            get {
                return ResourceManager.GetString("AddCustomerRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایستگاه ردیاب.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدوده.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حوزه.
        /// </summary>
        public static string Area1 {
            get {
                return ResourceManager.GetString("Area1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه شهرداری.
        /// </summary>
        public static string AreaCity {
            get {
                return ResourceManager.GetString("AreaCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه محدوده.
        /// </summary>
        public static string AreaGroup {
            get {
                return ResourceManager.GetString("AreaGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدوده ها.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مشتریان.
        /// </summary>
        public static string CustomerGroup {
            get {
                return ResourceManager.GetString("CustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتریان مسیر های دیگر.
        /// </summary>
        public static string CustomerOtherRoute {
            get {
                return ResourceManager.GetString("CustomerOtherRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتریان مسیر.
        /// </summary>
        public static string CustomerRoute {
            get {
                return ResourceManager.GetString("CustomerRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آنالیز مشتریان.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتریان بدون مسیر.
        /// </summary>
        public static string CustomerWithOutRoute {
            get {
                return ResourceManager.GetString("CustomerWithOutRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر روز.
        /// </summary>
        public static string DailyPath {
            get {
                return ResourceManager.GetString("DailyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبوردها.
        /// </summary>
        public static string Dashbord {
            get {
                return ResourceManager.GetString("Dashbord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف محدوده ها.
        /// </summary>
        public static string DeclareArea {
            get {
                return ResourceManager.GetString("DeclareArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف ها.
        /// </summary>
        public static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت دستگاه.
        /// </summary>
        public static string DeviceActivity {
            get {
                return ResourceManager.GetString("DeviceActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت با فاصله از مشتری.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه توزیع.
        /// </summary>
        public static string DistributArea {
            get {
                return ResourceManager.GetString("DistributArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موزع.
        /// </summary>
        public static string Distributer {
            get {
                return ResourceManager.GetString("Distributer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راننده.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی کردن.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ .
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از مبلغ.
        /// </summary>
        public static string FromPrice {
            get {
                return ResourceManager.GetString("FromPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از مسیر.
        /// </summary>
        public static string FromRoad {
            get {
                return ResourceManager.GetString("FromRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از ساعت.
        /// </summary>
        public static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاموش شدن GPS.
        /// </summary>
        public static string GpsOff {
            get {
                return ResourceManager.GetString("GpsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم سفارش.
        /// </summary>
        public static string LackOfOrder {
            get {
                return ResourceManager.GetString("LackOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم ویزیت.
        /// </summary>
        public static string LackOfVisit {
            get {
                return ResourceManager.GetString("LackOfVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشه.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مارکرها.
        /// </summary>
        public static string Markers {
            get {
                return ResourceManager.GetString("Markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string NotCheck {
            get {
                return ResourceManager.GetString("NotCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش با فاصله از مشتری.
        /// </summary>
        public static string OrderDistance {
            get {
                return ResourceManager.GetString("OrderDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش مشتری جدید.
        /// </summary>
        public static string OrderNewCustomer {
            get {
                return ResourceManager.GetString("OrderNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت خارج از مسیر.
        /// </summary>
        public static string OutOfLine {
            get {
                return ResourceManager.GetString("OutOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر حرکت.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف از مسیر.
        /// </summary>
        public static string RemoveCustomerRoute {
            get {
                return ResourceManager.GetString("RemoveCustomerRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر.
        /// </summary>
        public static string Road {
            get {
                return ResourceManager.GetString("Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مسیر.
        /// </summary>
        public static string RoadGroup {
            get {
                return ResourceManager.GetString("RoadGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر ها.
        /// </summary>
        public static string Roads {
            get {
                return ResourceManager.GetString("Roads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیربندی.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجرا.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب کنید ....
        /// </summary>
        public static string Select_Item {
            get {
                return ResourceManager.GetString("Select_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش مشتریان.
        /// </summary>
        public static string ShowCustomer {
            get {
                return ResourceManager.GetString("ShowCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان شروع.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرپرست.
        /// </summary>
        public static string Supperviser {
            get {
                return ResourceManager.GetString("Supperviser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان سفارش گیری.
        /// </summary>
        public static string TimeDuring {
            get {
                return ResourceManager.GetString("TimeDuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا ساعت.
        /// </summary>
        public static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آنالیز مسیر.
        /// </summary>
        public static string TrackerAnalaizing {
            get {
                return ResourceManager.GetString("TrackerAnalaizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازاریاب.
        /// </summary>
        public static string Visitor {
            get {
                return ResourceManager.GetString("Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه بازاریاب.
        /// </summary>
        public static string VisitorGroup {
            get {
                return ResourceManager.GetString("VisitorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر حرکت بازاریاب.
        /// </summary>
        public static string VisitorPath {
            get {
                return ResourceManager.GetString("VisitorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقف بدون مشتری.
        /// </summary>
        public static string WaitWithoutCustomer {
            get {
                return ResourceManager.GetString("WaitWithoutCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون فعالیت.
        /// </summary>
        public static string WithoutActivity {
            get {
                return ResourceManager.GetString("WithoutActivity", resourceCulture);
            }
        }
    }
}
